language: java

sudo: false

script: "mvn package --settings travis/settings.xml"

dist: trusty

jdk:
  - oraclejdk8

env:
  global:
  - secure: "kaW4Ti7cVD3jmLRYZi2h5sFrTRRay4yhfBp3HsZ6zaFpLW7WE5vKBD4vOmLGdyuALmKAjlRiTKsblb+74aSF79yvN/tltoVKlSSkMhbkkDmvAfAjbXgDjGqrRsv4FwUsQBuKzva92xzqY9uOt4ULPrgan7IqY58Sz1SdKg1X26Hvp0Nev7/ZgZTRaoVe49WugW5Zjg5wxcAhQBPCN4MIRGdEYCNjuD/k6X3L1LZw9e1zUnVey0OGmVKekXu9871Bj85INHlc9SO9DDtkku7B5DsupGsBEprMN/mDQQZlSlcrgDGuMxP+R6uzCnbSfuMsUVexsA8IvHHX1Q6ngzDtyHJff6GtdX0vk0qC/e+ZudSZBprZsTjUk5ZkaPWrl+mSjg2BjWXBsn1n3bl/v2rJ9O//l1ixhaaVQTdifRjCkVShyhlJqAPSQlBaizLFN6HE3XaraA+L2wDUh2OML/ZflRIb2Dy/bB1SeXXxTw/Sqr63CUva7qjULZGSRvRtr/An6IJheubO3QXjyyeEg5r6PU/i3pjDnMp4KEsGQ43rvghyyGDWLoZ0ykDG4dp7MyCmoTfqAPb2fwxS872dSKfUy5IRJRu2uNaGehREHMxMQF3s8rhLJZmjrohDd6fZIirHdAZBuXBMov3CME+aw0aI22ztn8r9NCDNvLnuQhSpx4M="
  - secure: "tBnnToN/osPWNixvzwfziN8hiy5J5+++kDlOgycGuUHy2NUINUOMCTfdkZOoT1evYfFAiBCNo5B/jW6r/Q4g7wJCgwPmWvCHm8p8aFO/zhVqX307KWr4PteouS0mD5fuFp7rJG/dJJzGEGHmOlWpb0GFUXnoBv0frqPEFh2ICHq375G5clVHrl+JIxNFH+6oJxbN+ped3lo5uJthGIilBPcBjQT7B1aJXGFF5Y8seUAvywBSgBkpfTy08/aE7qPM1QjAvzhMzVeOHsO/9V8XToYECoSGvlD3F8zooAlYU58y7Fnoav4tiAqdQ8hI97+Pu8tHg2qjRSTKOOitCdNQB+zl89mge8akyurHWc5vJkz1kATqPm30KT65ThHeXQq2UN6QkEQP+bo63PXTfQMjgk5+GzpEN9ILnW/oVwlDLQXXf0sFAJk+KM/fj8ORlC7etL9gOmmHRTjZf0BAKs0PIy4U3JqbQo0GvmOWx1pcvuo8iCb9zdjya1HArXZp0JOooF6UgpVMurw9Pb/1jd/bnIHFHbHjivuRJl3mb/5bhC6J3/IEM0aSn2NDZnCMGyyNrX8YZQjiXKuMP4XN0rk2dffjJv4EBFJ1ePRZFXzxQIfnSkBMKtB9DgDqbYVwLKwm65VjAURJLY3zJM042xbpWBAcMTXOwbSoxgz7Rjv0Qug="

after_success:
- chmod -R 777 ./travis/deploy-to-sonatype.sh
- ./travis/deploy-to-sonatype.sh
